Add 'join table' for visits PR
kkasaija/vet-clinic pull request #4
Opened 2022-12-15 22:16 UTC by Kasaija-Kenneth

### Milestone reached
- Added vets, visits, and specialties tables.
- Inserted data for specialties.
- Inserted data for visits.
- Ran queries as shown in the attached screen shots.

2022-12-15 22:47 UTC, tufoinnkuo10 requested changes
Hi @Kasaija-Kenneth 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ Descriptive pull request message



Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-12-15 22:47 UTC, tufoinnkuo10 commented on queries.sql
> +JOIN animals ON animals.owners_id = owners.id GROUP BY owners.full_name ORDER BY count DESC;
- [ ] Great job with the Queries. Please kindly add screenshots of your query results to the pull request description. this help the reviewer or viewer check them directly if the queries match

2022-12-15 22:47 UTC, tufoinnkuo10 commented on data.sql
> +
- [ ] please kinldy add data to the `specializations` table. you missed that part. 
nice work

2022-12-15 23:14 UTC, Kasaija-Kenneth commented on data.sql
> +
Noted, with thanks.

2022-12-15 23:45 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Ken,
### Great work on making the changes requested by a previous reviewer 👏 
### You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
## To Highlight 🎉
Git flow is followed. :heavy_check_mark:
PR has a title and description. :heavy_check_mark:
## To Improve 🙏
- [ ] [ OPTIONAL ] Please use [this](https://github.com/microverseinc/readme-template) new readme tempalate from Microverse in your current and all upcoming projects.
 
- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-15 23:45 UTC, SajjadAhmad14 commented on queries.sql
> +
Good job so far! You have added screenshots of query resuls in project directory but the requirement is to add them in PR description. Kindly add them so the next reviewer can check the results.

2022-12-16 00:23 UTC, Kasaija-Kenneth commented on queries.sql
> +
Noted, Thanks

2022-12-16 00:28 UTC, mwanawabangona approved these changes
Hi @Kasaija-Kenneth 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 00:30 UTC, Kasaija-Kenneth commented
Thank-you @mwanawabangona

2022-12-16 00:30 UTC, merged